name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Running a build Step"

  test:
    runs-on: ubuntu-latest
    steps:
     - name: Test Step
       run: echo "Running Test step"
  
